CREATE TABLE IF NOT EXISTS movie_genres(
    id SERIAL PRIMARY KEY NOT NULL,
    movie_id BIGINT NOT NULL REFERENCES movies(id),
    genre VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);